# -*- coding: utf-8 -*-
"""KeyBERT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qecXKpJz8RqChlwFdx_wgOhtMQxk3Bi1
"""

pip install pandas openpyxl
pip install keybert
pip install konlpy

#데이터 처리 라이브러리
import pandas as pd

#KeyBERT 라이브러리
from keybert import KeyBERT
from konlpy.tag import Komoran

# 엑셀 파일 읽기
file_path = '/content/drive/MyDrive/캡스톤/peerreview.xlsx'
df = pd.read_excel(file_path)

# 모든 셀의 내용을 하나의 문자열로 통합
feedback_test = ' '.join(df.astype(str).values.flatten())
sentences = df.astype(str).values.flatten().tolist()

print(feedback_test)
print(sentences)

#keyBERT 함수
def extract_keywords_keybert(text, top_n=10):
    kw_model = KeyBERT()
    komoran = Komoran()
    keywords = kw_model.extract_keywords(text, keyphrase_ngram_range=(1, 1), stop_words='english', use_maxsum=True, top_n=top_n)
    noun_keywords = []
    for keyword, score in keywords:
        pos_tags = komoran.pos(keyword)
        for word, pos in pos_tags:
            if pos.startswith('N'):
                noun_keywords.append(word)
                break
    return noun_keywords

raw_keywords_keybert = extract_keywords_keybert(feedback_test)
print("로우 데이터 키워드:", raw_keywords_keybert)
